=== halex02/boldensele-numerique/schemas/glossaire-v4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns="https://halex02.github.io/boldensele-numerique/ns/glossaire"
  targetNamespace="https://halex02.github.io/boldensele-numerique/ns/glossaire"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  >

  <!-- IMPORTS -->

  <xs:import namespace="http://purl.org/dc/elements/1.1/" schemaLocation="https://www.dublincore.org/schemas/xmls/qdc/dc.xsd"/>
  <!-- importation du schema des métadonnées du dublin core -->
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
  <!-- importation du schéma permettant d’utiliser l’attribut @xml:lang -->


  <!-- STRUCTURE GÉNÉRALE DU GLOSSAIRE -->

  <xs:element name="glossaire">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément racine du fichier de glossaire.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="metadonnees" maxOccurs="1"/>
        <xs:element ref="liste-termes" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="metadonnees">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément regroupant les métadonnées descriptives du glossaire.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dc:title">
          <xs:annotation>
            <xs:documentation xml:lang="fr">Titre du document.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="dc:creator">
          <xs:annotation>
            <xs:documentation>Auteur du document.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="dc:language">
          <xs:annotation>
            <xs:documentation xml:lang="fr">Langue principale du document.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="dc:source">
          <xs:annotation>
            <xs:documentation xml:lang="fr">Indication de la source du document (i.e. texte source,
	    référence du manuscrit, etc.).</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <!-- ORGANISATION DES ENTRÉES DU GLOSSAIRE -->

  <xs:element name="liste-termes">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément encapsulant les différents termes constituant le
      glossaire.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="terme" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="terme">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément décrivant une entrée du glossaire. 
      Une entrée regroupe les formes associées à un même terme, le nombre total de ses occurrences, 
      une définition ou un renvoi, ainsi que d’éventuels commentaires et références.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="liste-formes" maxOccurs="1"/>
        <xs:element ref="nombre-occurrences" maxOccurs="1"/>
        <xs:choice>
          <xs:element ref="definition" maxOccurs="1"/>
          <xs:element ref="renvoi" maxOccurs="1"/>
        </xs:choice>
        <xs:element ref="commentaires" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="reference" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>


  <!-- FORMES, DÉFINITION, RENVOIS ET RÉFÉRENCES -->

  <xs:element name="liste-formes">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément encapsulant les différentes formes recensées pour un terme du glossaire.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="forme" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="forme">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément décrivant une forme liée à un terme. Le type de la forme précise s’il s’agit du lemme de l’entrée, d’une forme fléchie attestée ou d’une variante.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="graphie" maxOccurs="1"/>
        <xs:element ref="categorie_grammaticale" maxOccurs="1"/>
        <xs:element ref="liste-attestations" maxOccurs="1"/>
        <xs:element ref="commentaires" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="lemme"/>
            <xs:enumeration value="flexion"/>
            <xs:enumeration value="variante"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="graphie">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément servant à encoder la graphie d’une forme.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute ref="xml:lang"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="nombre-occurrences" type="xs:positiveInteger">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Nombre d’occurrences du terme présentes dans le texte
      source.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="definition" type="xs:string">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément de définition/traduction du terme.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="renvoi">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément permettant de renvoyer d’une entrée à une autre entrée du glossaire au moyen de son identifiant,
      notamment pour gérer les synonymes.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="idref" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="reference">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément encodant une référence bibliographique ou lexicographique associée à un terme.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dc:source" maxOccurs="1"/>
        <xs:element ref="dc:identifier" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="commentaires" type="xs:string">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément permettant de placer des notes explicatives
      diverses.</xs:documentation>
    </xs:annotation>
  </xs:element>


  <!-- ATTESTATIONS ET LOCALISATION -->

  <xs:element name="liste-attestations">
    <xs:annotation>
      <xs:documentation xml:lang="fr">
	Regroupement des attestations d’une forme donnée.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="absence-attestation" minOccurs="1" maxOccurs="1"/>
          <xs:element ref="attestation" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="attestation">
    <xs:annotation>
      <xs:documentation xml:lang="fr">
      Encodage d’une attestation avec sa position et possibilité de créer un lien vers l’occurrence dans le texte.
      L’attribut @idref, lorsqu’il est renseigné, permet de relier l’attestation à une occurrence identifiée dans le texte encodé.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="localisation" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="idref" type="xs:IDREF" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="absence-attestation">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément indiquant qu’aucune occurrence de la forme n’est attestée dans le texte, 
      bien que la forme soit conservée dans le glossaire, en particulier pour de mise en adresse d’une forme lemmatisée.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="localisation">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément contenant la positiion d’une forme fléchie dans
      le texte source.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element ref="numero-vers"/>
          <xs:element ref="ref-folio"/>
          <xs:element ref="numero-page"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="numero-vers" type="xs:positiveInteger">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Élément permettant d’indiquer un numéro de vers dans le texte
      source.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="ref-folio">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Référence de folio avec indication au moyen d’attributs du recto/verso (obligatoire) et des colonnes (facultative)</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:positiveInteger">
          <xs:attribute name="cote" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="r"/>
                <xs:enumeration value="v"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="colonne" use="optional">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[a-z]"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="numero-page" type="xs:positiveInteger">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication d’un numéro de page</xs:documentation>
    </xs:annotation>
  </xs:element>


  <!-- CATÉGORIES GRAMMATICALES -->

  <xs:element name="categorie_grammaticale">
    <xs:annotation>
      <xs:documentation xml:lang="fr">
	Informations grammaticales sur une forme d’un terme.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:choice>
        <xs:element ref="substantif"/>
        <xs:element ref="adjectif"/>
        <xs:element ref="verbe"/>
        <xs:element ref="adverbe"/>
        <xs:element ref="pronom"/>
        <xs:element ref="preposition"/>
        <xs:element ref="article"/>
        <xs:element ref="interjection"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="substantif">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Informations grammaticales sur un substantif</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="genre"/>
        <xs:element ref="nombre"/>
        <xs:element ref="cas" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="adjectif">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Informations grammaticales sur un adjectif</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="genre" minOccurs="0"/>
        <xs:element ref="nombre" minOccurs="0"/>
        <xs:element ref="cas" minOccurs="0"/>
        <xs:element ref="degre" minOccurs="0"/>
        <xs:element ref="construction" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="verbe">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Informations grammaticales sur un verbe</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mode" minOccurs="1"/>
        <xs:element ref="temps" minOccurs="1"/>
        <xs:element ref="voix" minOccurs="0"/>
        <xs:element ref="personne" minOccurs="0"/>
        <xs:element ref="construction" minOccurs="0"/>
        <xs:element ref="genre" minOccurs="0"/>
        <xs:element ref="nombre" minOccurs="0"/>
        <xs:element ref="cas" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="adverbe">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Informations grammaticales sur un adverbe</xs:documentation>
    </xs:annotation>
    <xs:complexType>
    <xs:sequence>
      <xs:element ref="degre" minOccurs="0"/>
    </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="pronom">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Informations grammaticales sur un pronom</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="preposition">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Informations grammaticales sur une préposition</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="construction" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="article">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Informations grammaticales sur un article</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="interjection">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Informations grammaticales sur une interjection</xs:documentation>
    </xs:annotation>
  </xs:element>


  <!-- TRAITS GRAMMATICAUX ÉLÉMENTAIRES -->

  <xs:element name="genre">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication du genre d’un nom, d’un adjectif, etc.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="masculin"/>
        <xs:enumeration value="féminin"/>
        <xs:enumeration value="neutre"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="nombre">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication du nombre d’un nom, d’un adjectif, etc.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="singulier"/>
        <xs:enumeration value="pluriel"/>
        <xs:enumeration value="duel"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="cas">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication du cas, i.e. désinence indiquant la
      fonction grammaticale d’un substantif ou d’un adjectif.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="sujet"/>
        <xs:enumeration value="régime"/>
        <xs:enumeration value="nominatif"/>
        <xs:enumeration value="vocatif"/>
        <xs:enumeration value="accusatif"/>
        <xs:enumeration value="génitif"/>
        <xs:enumeration value="datif"/>
        <xs:enumeration value="ablatif"/>
        <xs:enumeration value="locatif"/>
        <xs:enumeration value="instrumental"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="degre">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication du degré d’un adjectif ou d’un adverbe, c’est à
      dire s’il est au positif, au comparatif ou au superlatif.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="simple"/>
        <xs:enumeration value="comparatif"/>
        <xs:enumeration value="superlatif"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="temps">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication des temps verbaux.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="présent"/>
        <xs:enumeration value="passé"/>
        <xs:enumeration value="passé simple"/>
        <xs:enumeration value="futur"/>
        <xs:enumeration value="futur I"/>
        <xs:enumeration value="futur II"/>
        <xs:enumeration value="imparfait"/>
        <xs:enumeration value="forme en -ant"/>
        <xs:enumeration value="parfait"/>
        <xs:enumeration value="plus-que-parfait"/>
        <xs:enumeration value="futur antérieur"/>
        <xs:enumeration value="aoriste"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="mode">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication des modes verbaux.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="indicatif"/>
        <xs:enumeration value="subjonctif"/>
        <xs:enumeration value="conditionnel"/>
        <xs:enumeration value="participe"/>
        <xs:enumeration value="infinitif"/>
        <xs:enumeration value="impératif"/>
        <xs:enumeration value="optatif"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="personne">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication de la personne d’une forme sous la forme de nombre entier:
      - 1, 2, 3 pour les personnes du singulier ;
      - 4, 5 et 6 pour celle du pluriel ;
      - 7, 8, 9 pour celle du duel pour les langues où ce nombre est présent.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger">
        <xs:pattern value="[1-9]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="construction" type="xs:string">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication des constructions verbales (ou autres): transitif,
      intransitif, réfléchi, etc. On peut aussi indiquer le type de complément d’un adjectif ou
      d’un adverbe.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="voix">
    <xs:annotation>
      <xs:documentation xml:lang="fr">Indication de la voix d’un verbe : active, passive, moyenne.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="active"/>
        <xs:enumeration value="passive"/>
        <xs:enumeration value="pronominale"/>
        <xs:enumeration value="moyenne"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

</xs:schema>

=== halex02/boldensele-numerique/work/glossaire-output.xml
<?xml version="1.0" encoding="UTF-8"?>
<glossaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../schemas/glossaire-v4.xsd"
           xml:lang="fr">
   <metadonnees>
      <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">Glossaire</dc:title>
      <dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Moret Alexandre</dc:creator>
      <dc:language xmlns:dc="http://purl.org/dc/elements/1.1/">fr</dc:language>
      <dc:source xmlns:dc="http://purl.org/dc/elements/1.1/">Guillaume de Boldensele</dc:source>
   </metadonnees>
   <liste-termes>
      <terme id="gls-0001">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la"/>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0005">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
                  <attestation idref="#w-0013">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
                  <attestation idref="#w-0016">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
                  <attestation idref="#w-0104">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
                  <attestation idref="#w-0114">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>5</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0002">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">abinuicem</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0042">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0003">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">aeris</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0127">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0004">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">alexandre</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0097">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0005">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">angelicis</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0082">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0006">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">apparenti</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0091">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0007">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">armatam</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0022">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0008">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">ascendi</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0025">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0009">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">asserunt</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0094">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0010">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">attingit</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0050">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0011">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">austram</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0048">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0012">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">beatus</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0073">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
         <nombre-occurrences>1</nombre-occurrences>
         <definition>À compléter</definition>
      </terme>
      <terme id="gls-0013">
         <liste-formes>
            <forme type="lemme">
               <graphie xml:lang="la">bene</graphie>
               <categorie_grammaticale>À compléter</categorie_grammaticale>
               <liste-attestations>
                  <attestation idref="#w-0021">
                     <localisation>
                        <ref-folio cote="v">236</ref-folio>
                     </localisation>
                  </attestation>
               </liste-attestations>
            </forme>
         </liste-formes>
